Foretagsanmalan design
ernum/ddagen pull request #10
Opened 2023-02-18 09:16 UTC by Eggetxd

råkade göra en pull request till stora hemsidan... hehe fixat nu

2023-02-21 23:32 UTC, ernum requested changes

2023-02-21 23:32 UTC, ernum commented on src/pages/f%C3%B6rf%C3%B6retag.js
> +            </div>
This branch probably shouldn't include changes to the "for companies".

2023-02-21 23:32 UTC, ernum commented on tailwind.config.js
> +        'webBackground': "url('/img/website-background.svg')",
This background isn't high-quality enough for the website. We should probably figure out how to tweak it to make it clearer.

2023-02-21 23:32 UTC, ernum commented on src/components/CompanyForm.js
>                      />
Some inputs need the "[pattern](https://www.w3schools.com/tags/att_input_pattern.asp)" attribute to disallow companies from inputting the wrong format. We can use simple regexes for OrgNum, for example. Can you fix this in the pull request, or should we create a new one?

2023-02-22 12:22 UTC, Eggetxd commented on src/pages/f%C3%B6rf%C3%B6retag.js
> +            </div>
yes, I forgot to change it from the last branch

2023-02-22 12:23 UTC, Eggetxd commented on tailwind.config.js
> +        'webBackground': "url('/img/website-background.svg')",
I took it from figma so it is the highest quality I could get easily.

2023-02-22 12:25 UTC, Eggetxd commented on src/components/CompanyForm.js
>                      />
hmm I can take a look at that but I'll do that in a later pull request.

2023-02-22 16:24 UTC, Eggetxd commented on src/pages/f%C3%B6rf%C3%B6retag.js
> +            </div>
I have now removed the changes linked to the "for companies" page.

2023-02-23 11:48 UTC, Eggetxd commented on src/components/CompanyForm.js
>                      />
I have now changed the styling to support pattern which I have implemented for the email input. I am not sure of the format on the other inputs so I have not done them but it is as simple as writing: pattern="[regex]" in the desired input

2023-02-23 19:57 UTC, mathiasmagnusson commented on src/components/CompanyForm.js
>                      />
For emails, web browsers do this without having to specify a regex. Can be selected with e.g. `invalid:border-red-700`

2023-02-24 13:21 UTC, mathiasmagnusson requested changes
Also make sure to rebase/merge this and make it a `.tsx` file

2023-02-24 13:21 UTC, mathiasmagnusson commented on src/components/CompanyForm.js
> +                    <button className="bg-cerise hover:bg-cerise-light text-white font-bold py-2 px-4 rounded-full focus:outline-none focus:shadow-outline" onClick={(e) => addCompanyDocument(e)}>
This should be an `input` with type `submit`, and the `onClick` here should instead be an `onSubmit` on the form

2023-02-24 13:21 UTC, mathiasmagnusson commented on src/components/CompanyForm.js
> +                <div className="my-16 relative">
It would be nice to put this in a separate, non-exported function to avoid repetition

2023-02-24 13:55 UTC, Eggetxd commented on tailwind.config.js
> +        'webBackground': "url('/img/website-background.svg')",
smart, I'll do that!

2023-02-24 14:08 UTC, Eggetxd commented on tailwind.config.js
> +        'webBackground': "url('/img/website-background.svg')",
det tar MYCKET längre tid att ladda in den nu...

2023-02-24 15:25 UTC, Eggetxd commented on src/components/CompanyForm.js
>                      />
fixed

2023-02-24 15:31 UTC, Eggetxd commented on src/components/CompanyForm.js
> +                    <button className="bg-cerise hover:bg-cerise-light text-white font-bold py-2 px-4 rounded-full focus:outline-none focus:shadow-outline" onClick={(e) => addCompanyDocument(e)}>
fixed!

2023-02-25 19:59 UTC, mathiasmagnusson approved these changes
The background is still problematic, but I think we can commit this until we have a better one.

2023-02-25 21:48 UTC, mathiasmagnusson commented
Rebased onto `develop`

2023-02-27 12:52 UTC, ernum commented on src/pages/f%C3%B6retagsanm%C3%A4lan.tsx
> +            ">{t.contact}</a>
The padding on the y-axis should be less in my opinion. It's quite low.

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/66337956/221568574-ecc3ff85-85d8-47ac-bf49-c9ea7aabc5d5.png">

2023-02-27 15:27 UTC, ernum requested changes

2023-02-27 15:27 UTC, ernum commented on src/components/CompanyForm.tsx
> +            await db.collection("company").add({
This should be 'exhibitor'

2023-02-27 15:37 UTC, ernum commented
LGTM!

2023-02-27 15:39 UTC, merged