Navbar design for small screens
ernum/ddagen pull request #14
Opened 2023-02-23 19:51 UTC by mathiasmagnusson

2023-02-24 23:52 UTC, ernum requested changes

2023-02-24 23:52 UTC, ernum commented on src/components/Navbar.tsx
> +                        >{nav.companyForm}</Link>
The text in this button should be centred. It's especially visible in the English version of the site. 
![image](https://user-images.githubusercontent.com/66337956/221322370-592be139-341b-4db3-8a03-0bdab12ff839.png)

2023-02-25 16:57 UTC, mathiasmagnusson commented on src/components/Navbar.tsx
> +                        >{nav.companyForm}</Link>
Whoops, i missed to check the english version on a phone hehe.

I'll fix!

2023-02-25 22:01 UTC, ernum approved these changes
LGTM!

2023-02-25 22:01 UTC, merged