feat(ddagen): Implement homepage design
ernum/ddagen pull request #20
Opened 2023-02-26 08:57 UTC by ernum

Design not done yet. Minor changes to be made. Also not completely responsive.

2023-02-26 21:07 UTC, mathiasmagnusson requested changes

2023-02-26 21:07 UTC, mathiasmagnusson commented on tailwind.config.js
> +    backgroundImage: {
This removes the `bg-gradient-to-t` class (since this replaces all existing classes for `background-image`s), which is why the nav bar's gradient disappeared. Move this object up to the `extend` part instead.

2023-02-28 15:34 UTC, mathiasmagnusson approved these changes

2023-03-01 14:14 UTC, mathiasmagnusson commented on src/pages/index.tsx
> +            className="flex flex-colitems-center py-12 mb-16"
Typo?

2023-03-01 14:14 UTC, mathiasmagnusson commented on src/pages/index.tsx
> +            <div className="md:grid md:grid-rows-[repeat(26,_minmax(auto,1fr))] md:grid-cols-[repeat(32,_minmax(auto,1fr))] max-md:p-2 bg-white/80 w-full">
The underscores after the commas aren't necessary here.

2023-03-01 14:14 UTC, mathiasmagnusson commented on src/pages/index.tsx
> +              <div className="md:col-[3/20] md:row-[3/15] z-49">
`z-49` doesn't exist, so either remove if it works or use `z-40`

2023-03-01 14:42 UTC, ernum commented on src/pages/index.tsx
> +            className="flex flex-colitems-center py-12 mb-16"
Yep

2023-03-01 15:40 UTC, rikaznismi commented
The pink layer, is seen in the background.
![bild](https://user-images.githubusercontent.com/58601215/222188434-9ff13b35-c456-4f42-bd44-65b10d49c2c4.png)

2023-03-01 16:20 UTC, rikaznismi commented
@ernum 
I think it looks good. But perhaps to make it more similar to the design on figma
- make the font of the bottom header, "Företagsrepresentant" larger,
- make the bottom header a bit closer to the below paragraph 

Otherwise I approve.

2023-03-01 17:17 UTC, mathiasmagnusson requested changes
Also, i think it would be good to set `max-w-5xl` on the main thing to make it look better on bigger screens

2023-03-01 17:17 UTC, mathiasmagnusson commented on src/pages/_app.tsx
> +        bg-top bg-no-repeat bg-auto
I don't think this works at all. I think setting `bg-repeat` is better (though not amazing)

2023-03-01 19:41 UTC, mathiasmagnusson approved these changes

2023-03-01 19:44 UTC, merged