feat(app): Add email confirmation and update homepage image #163
ernum/ddagen pull request #27
Opened 2023-03-04 17:28 UTC by ernum

2023-03-04 17:29 UTC, ernum commented
Have not really checked grammar so fill free to to update if something is missed.

2023-03-04 22:52 UTC, mathiasmagnusson requested changes
​

2023-03-04 22:52 UTC, mathiasmagnusson commented
Will write some stuff tomorrow

2023-03-05 10:47 UTC, mathiasmagnusson requested changes

2023-03-05 10:47 UTC, mathiasmagnusson commented on src/components/CompanyForm.tsx
> +            "
What is this indentation? (same above)
:p

2023-03-05 10:47 UTC, mathiasmagnusson commented on src/components/CompanyForm.tsx
> +      console.log(err);
Would be nice to show an error here. Perhaps the `error` could be something like `"db" | "email" | null` instead of the boolean we have now.

2023-03-05 10:47 UTC, mathiasmagnusson commented on src/components/CompanyForm.tsx
> +      sendConfirmationEmail();
Also, this should probably be in the `try` part, after the `collection(...).add`.

2023-03-05 10:47 UTC, mathiasmagnusson commented on src/pages/api/sendEmail.tsx
> +        key: process.env.NEXT_PUBLIC_SPAM_API_KEY,
The `NEXT_PUBLIC` prefix makes this available on the client, which it may not be.
Same goes for the spam url, but that's not critical.

2023-03-05 10:47 UTC, mathiasmagnusson commented on src/pages/api/sendEmail.tsx
> +      body: JSON.stringify({
This makes anyone able to send any email using this api call. We should move as many fields as possible (so all except the form fields) to be put into the backend.

2023-03-05 10:47 UTC, mathiasmagnusson commented on src/locales/en.ts
> +      <p>X</p>`;
This should probably be changed.

2023-03-05 10:47 UTC, mathiasmagnusson commented on src/locales/en.ts
> +        <li>Company Name: ${companyName}</li>
Emails are pretty restricted so I'm unsure how big of a problem this is, but this does open up for some injection attacks.
I'm guessing that at least one could put in a style tag that hides the hardcoded html and put a bit of whatever in the email.

2023-03-05 11:11 UTC, mathiasmagnusson commented on src/components/CompanyForm.tsx
> -            return;
Also, without this return, the user will be redirected even in case of an error.

2023-03-05 12:36 UTC, mathiasmagnusson commented on src/locales/en.ts
> +        <li>Company Name: ${companyName}</li>
Nvm - in some step this get converted to markdown and then the non-rendered markdown gets put in the email.

2023-03-05 12:42 UTC, mathiasmagnusson approved these changes

2023-03-05 12:42 UTC, mathiasmagnusson commented
![image](https://user-images.githubusercontent.com/32957299/222961085-a0912a8c-32cd-4a02-b63a-f9787b57c307.png)

2023-03-05 12:46 UTC, rikaznismi commented
XD

2023-03-05 12:47 UTC, merged