Add responsive footer
ernum/ddagen pull request #9
Opened 2023-02-18 04:29 UTC by rikaznismi

The footer is almost complete(99%). The only issue left is when the width is 670 or less, an x axis scrollbar appears, and if scrolled
a white bar is there to the right. However, when I try this footer without the navbar on, no scrollbar or white bar appears. But if I try with the navbar on only, a scrollbar still appears, but maybe this is intentional. 
I am not certain if the problem lies with the footer or with the navbar.

2023-02-18 04:40 UTC, rikaznismi commented
Try reviewing the layout as well, I changed it on width 768 and down.

2023-02-20 10:32 UTC, Eggetxd commented
I think the scrollbar problem is from the navbar. If the scrollbar doesn't appear when you use the footer without the navbar, the gooter should be fine

2023-02-21 23:19 UTC, ernum requested changes

2023-02-21 23:19 UTC, ernum commented on src/components/Footer.js
> +      "
Use the "[prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)" plugin in vscode to standardise the formatting (add format on save to do this automatically).

2023-02-21 23:19 UTC, ernum commented on src/components/Footer.js
> +      bg-[url('/img/footer-shape1.svg')]
Since the art team has changed the background of the footer to a straight line, I think using the bg-[#636363] is better than using an SVG.

2023-02-21 23:19 UTC, ernum commented on src/components/Footer.js
> +          </div>
The social media logos don't seem to be the same size. Think we should fix that

2023-02-21 23:19 UTC, ernum commented on src/components/Footer.js
> +            <FooterLink href="about">{footer.header} </FooterLink>
The text has been updated again so we should probably change this. Also, the spacing between the different sections seems to have changed a bit too.

2023-02-21 23:19 UTC, ernum commented on src/pages/_app.js
> +import Footer1 from '@/components/Footer1';
This doesn't seem to be used anymore. Should probably be removed

2023-02-21 23:19 UTC, ernum commented on src/pages/_app.js
> +
Apply the "[prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)" format here too.

2023-02-24 15:50 UTC, rikaznismi commented on src/components/Footer.js
> +      "
Done, did formatting with "prettier".

2023-02-24 15:52 UTC, rikaznismi commented on src/pages/_app.js
> +
Done

2023-02-24 15:52 UTC, rikaznismi commented on src/pages/_app.js
> +import Footer1 from '@/components/Footer1';
Done

2023-02-24 15:52 UTC, rikaznismi commented on src/components/Footer.js
> +            <FooterLink href="about">{footer.header} </FooterLink>
Done

2023-02-24 15:52 UTC, rikaznismi commented on src/components/Footer.js
> +          </div>
Done

2023-02-24 15:52 UTC, rikaznismi commented on src/components/Footer.js
> +      bg-[url('/img/footer-shape1.svg')]
Done

2023-02-24 15:53 UTC, rikaznismi commented
I think the issues have been resolved now, please review again.

2023-02-24 23:46 UTC, ernum approved these changes
LGTM!

2023-02-24 23:46 UTC, merged